name: bloc_online_store
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  file_picker: ^8.0.0+1
  http: ^1.2.2
  intl: ^0.20.1
  image_picker: ^1.0.2
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
