name: bloc_online_store
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  add_to_cart_animation: ^2.0.4
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  device_preview_minus: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_map: ^7.0.2
  flutter_gen: ^5.8.0
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.10
  file_picker: ^8.0.0+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  location: ^7.0.0
  latlong2: ^0.9.0
  image_picker: ^1.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.1.2
  smooth_page_indicator: ^1.2.0+3
  flutter_skeleton_plus: ^0.0.2
  whitecodel_reels: ^0.0.6

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_native_splash:
  color: "#ffffff"
  image: android\app\src\main\res\mipmap-xxxhdpi\ic_launcher_foreground.png
  color_dark: "#121212"
  image_dark: android\app\src\main\res\mipmap-xxxhdpi\ic_launcher_foreground.png

  android_12:
    image: android\app\src\main\res\mipmap-xxxhdpi\ic_launcher_foreground.png
    icon_background_color: "#ffffff"
    image_dark: android\app\src\main\res\mipmap-xxxhdpi\ic_launcher_foreground.png
    icon_background_color_dark: "#121212"

  web: false

fonts:
  - family: Roboto-Regular
    fonts:
      - asset: fonts/Roboto-Regular.ttf
