name: bloc_online_store
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  add_to_cart_animation: ^2.0.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  device_preview_minus: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  file_picker: ^8.0.0+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  location: ^7.0.0
  latlong2: ^0.9.0
  image_picker: ^1.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
